### ISSUE TITLE
Clean UP & Dockerization eos7w6n

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos7w6n#5]

**Comment by emmakodes** [comment]
Hello, @GemmaTuron this model didn't work initially because `conda install -c conda-forge rdkit=2021.03.4` was failing. So I had to instead use `pip install rdkit==2023.3.1` and it was able to fetch and make predictions successfully. I changed the api to run in service.py since it was using the predict method. The model was able to fetch and make predictions successfully using the run api:
```
(ersilia) emma@DESKTOP-VN7367J:~/ersiliamodel$ ersilia serve eos7w6n
🚀 Serving model eos7w6n: grover-embedding

   URL: http://127.0.0.1:47283
   PID: 13032
   SRV: conda

👉 To run model:
   - run

💁 Information:
   - info
```
[eos7w6n_pred.csv](https://github.com/ersilia-os/eos7w6n/files/12003000/eos7w6n_pred.csv)
[eos7w6n_fetch_log.txt](https://github.com/ersilia-os/eos7w6n/files/12003003/eos7w6n_fetch_logs.txt)

When I try to edit `run.sh` to accept command line values and `service.py` to point to run.sh file, I get the following error:
[eos7w6n_fetch.log](https://github.com/ersilia-os/eos7w6n/files/12003099/eos7w6n_fetch.log) (I upload the file because it might be too long to post the error message)

**Comment by emmakodes** [comment]
I installed the model source code from the author's repo to my system to see how it works. I ran predictions for smiles csv and I get the following logs:  
[grover.txt](https://github.com/ersilia-os/eos7w6n/files/12009133/grover.txt)
same logs I got when I edited `run.sh` and `service.py` files above but with an output `fp.npz`. I guess the `fp.npz output is the output predictions but saved as a numpy array.

**Comment by emmakodes** [comment]
@GemmaTuron In summary, `run.sh` and `service.py` works with the following code I have now in my forked repo [run.sh](https://github.com/emmakodes/eos7w6n/blob/main/model/framework/run.sh) [service.py](https://github.com/emmakodes/eos7w6n/blob/main/src/service.py) but when I edit run.sh to accept command line values and service.py to point to run.sh file then I get same log as running the author's source but without any output predictions.

**Comment by GemmaTuron** [comment]
I see! 
@miquelduranfrigola do you think we could leave it as it is?

**Comment by GemmaTuron** [comment]
@emmakodes 

Let's not touch it, leave the original piece of code and we'll live with that to avoid further issues. If there are minor changes done (like, removing unnecessary files, adapting the .gitattributes) open a PR and we'll merge it

**Comment by emmakodes** [comment]
Okay @GemmaTuron let me do those now and open a PR

**Comment by emmakodes** [comment]
Hello @GemmaTuron I have made the PR

**Comment by GemmaTuron** [comment]
This model is completed!
